"""Phase 5 — Generate outputs/report.md from stats and cost data."""

import json
import os
from datetime import datetime
from pathlib import Path

from configs import resolve_path
from pipeline.checkpoint import Checkpoint


def generate_report(state: object) -> None:
    """Generate outputs/report.md with run summary."""
    stats_path = resolve_path("stats")
    cost_path = resolve_path("cost")
    report_path = resolve_path("report")
    train_path = resolve_path("train_output")
    eval_path = resolve_path("eval_output")

    # Read stats
    stats = {}
    if os.path.exists(stats_path):
        with open(stats_path) as f:
            stats = json.load(f)

    # Read cost
    cost = {}
    if os.path.exists(cost_path):
        with open(cost_path) as f:
            cost = json.load(f)

    # File sizes
    train_size = os.path.getsize(train_path) if os.path.exists(train_path) else 0
    eval_size = os.path.getsize(eval_path) if os.path.exists(eval_path) else 0

    # Build report
    lines = [
        "# finetuner.dev — Run Report",
        "",
        f"**Run ID:** {state.run_id}",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Elapsed:** {state.elapsed}",
        "",
        "---",
        "",
        "## Sample Counts",
        "",
        f"- **Total accepted:** {stats.get('total_accepted', 0)}",
        f"- **Training samples:** {stats.get('train_count', 0)}",
        f"- **Evaluation samples:** {stats.get('eval_count', 0)}",
        f"- **Single-turn:** {stats.get('single_count', 0)}",
        f"- **Multi-turn:** {stats.get('multi_count', 0)}",
        "",
        "## Acceptance Rate",
        "",
        f"- **Accepted:** {state.accepted}",
        f"- **Rejected:** {state.rejected}",
        f"- **Errors:** {state.errors}",
        f"- **Acceptance rate:** {state.acceptance_rate:.1%}",
        "",
        "## Score Distribution",
        "",
    ]

    buckets = state.score_buckets if hasattr(state, "score_buckets") else {}
    for bucket, count in buckets.items():
        lines.append(f"- **{bucket}:** {count}")
    lines.append("")

    lines.extend([
        "## Cost Breakdown",
        "",
        f"- **User tokens:** {cost.get('user_tokens', 0):,}",
        f"- **Teacher tokens:** {cost.get('teacher_tokens', 0):,}",
        f"- **Validator tokens:** {cost.get('validator_tokens', 0):,}",
        f"- **Total cost:** ${cost.get('total_cost_usd', 0):.4f}",
        "",
        "## Final Dataset",
        "",
        f"- **Train:** `{train_path}` ({train_size:,} bytes)",
        f"- **Eval:** `{eval_path}` ({eval_size:,} bytes)",
        "",
        "---",
        "",
        "*Generated by finetuner.dev*",
    ])

    report_content = "\n".join(lines)

    Path(report_path).parent.mkdir(parents=True, exist_ok=True)
    with open(report_path, "w") as f:
        f.write(report_content)

    # Mark phase 5 complete
    checkpoint = Checkpoint()
    checkpoint.mark_phase_complete(5)
